#!/usr/bin/env sh

set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
OUT_FILE="$ROOT_DIR/wifi_config.py"

: "${WIFI_SSID:?WIFI_SSID is required}"
: "${WIFI_PASSWORD:?WIFI_PASSWORD is required}"

escape_py_string() {
    # Escape backslashes and single quotes for a single-quoted Python string.
    printf '%s' "$1" | sed "s/\\\\/\\\\\\\\/g; s/'/\\\\'/g"
}

SSID_ESCAPED=$(escape_py_string "$WIFI_SSID")
PASS_ESCAPED=$(escape_py_string "$WIFI_PASSWORD")

cat >"$OUT_FILE" <<EOF
# Auto-generated by tools/generate_wifi_config.sh
# Do not commit this file.

WIFI_SSID = '$SSID_ESCAPED'
WIFI_PASSWORD = '$PASS_ESCAPED'
EOF

echo "Generated $OUT_FILE"